### ISSUE TITLE
Too Many Requests (RFC 6585)

### ISSUE THREAD

**Issue by fontikar** [umatter/OpenAIR#6] opened 2023-08-11 06:06 UTC
Hi {OpenAIR} maintainers 👋 

Thanks for creating this package! I'm really looking forward to getting it up and running!
Currently I am struggling with starting a chat! Reprex below

Do you have a workaround this HTTP error? 

Thank you in advance! 

``` r
library(TheOpenAIR)

openai_api_key(Sys.getenv("OPENAI_API_KEY"))

chat("What is a R package?")
#> HTTP error : Too Many Requests (RFC 6585)
#> Error in messages(.): Invalid parameter value. Expecting list or chatlog object.
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by JLDC** [comment] 2023-08-12 08:33
Hi @fontikar 

See my reply to the following issue: https://github.com/umatter/OpenAIR/issues/5#issuecomment-1661734363. This is the same problem you are currently having. The error message indicates that the issue does not directly stem from the R package. We cannot reproduce this error on our side.

If you are sure that everything is in order with your OpenAI API (i.e., you can make requests using other methods) and if you have any further explanation on how we can try to reproduce this issue, please let me know here.

Otherwise, I will close this issue in a few days.

**Closed as completed** 2023-08-21 14:08 UTC
